"""
Module build advanced

This module provides functions to construct a colored De Bruijn graph
and compact it into unitigs.

The graph is built from multiple FASTA files, where each file is associated
with a distinct color. Unitigs are generated by extending k-mers in both
directions when possible.
"""

from Bio import SeqIO


def dbg_builder(fasta_file: str, color: int, k: int, dbg: dict):
    """
    Update a colored De Bruijn graph using a single FASTA file.

    This function parses a FASTA file, extracts all k-mers of size `k`,
    and inserts them into a colored De Bruijn graph while associating
    each k-mer with a color identifier.

    
    Parameters:

    fasta_file : str
        Path to a FASTA file.
    color : int
        Integer identifier representing the position of the file
        in the original input list.
    k : int
        Length of the k-mers.
    dbg : dict
        Dictionary representing the colored De Bruijn graph.

        
    Returns:

    dict
        Updated colored De Bruijn graph.
    """
    for record in SeqIO.parse(fasta_file, "fasta"):
        seq = str(record.seq)

        # Sliding window extraction of k-mers
        for i in range(0, len(seq) - k + 1):
            kmer = seq[i: i + k]

            # Insert the k-mer and associate it with the current color
            if kmer not in dbg.keys():
                dbg[kmer] = [color]
            elif color not in dbg[kmer]:
                dbg[kmer].append(color)

    return dbg


def right_neighbors(kmer, dbg):
    """
    Identify right neighbors of a k-mer in the De Bruijn graph.

    
    Parameters:

    kmer : str
        Input k-mer.
    dbg : dict or set
        Collection of k-mers representing the graph.

        
    Returns:
    list of str

        List of right neighboring k-mers.
    """
    res = []
    for letter in ["A", "C", "G", "T"]:
        neighbor = kmer[1:] + letter
        if neighbor in dbg:
            res.append(neighbor)
    return res


def left_neighbors(kmer, dbg):
    """
    Identify left neighbors of a k-mer in the De Bruijn graph.

    
    Parameters:

    kmer : str
        Input k-mer.
    dbg : dict or set
        Collection of k-mers representing the graph.

        
    Returns:

    list of str
        List of left neighboring k-mers.
    """
    res = []
    for letter in ["A", "C", "G", "T"]:
        neighbor = letter + kmer[:-1]
        if neighbor in dbg:
            res.append(neighbor)
    return res


def right_unitig(kmer, list_kmer):
    """
    Extend a k-mer to the right to form a unitig.

    
    Parameters:

    kmer : str
        Starting k-mer.
    list_kmer : set
        Set of all k-mers in the graph.

        
    Returns:

    tuple
        A tuple containing:
        - the constructed unitig (str),
        - the set of k-mers used to build it.
    """
    unitig = kmer
    used = {kmer}
    current = kmer

    while True:
        neighbors = right_neighbors(current, list_kmer)
        if len(neighbors) != 1:
            return unitig, used

        nxt = neighbors[0]
        unitig += nxt[-1]
        used.add(nxt)

        if nxt == kmer or nxt == current:
            return unitig, used

        if (
            len(left_neighbors(nxt, list_kmer)) != 1
            or len(right_neighbors(nxt, list_kmer)) != 1
        ):
            return unitig, used

        current = nxt


def left_unitig(kmer, list_kmer):
    """
    Extend a k-mer to the left to form a unitig.

    
    Parameters:

    kmer : str
        Starting k-mer.
    list_kmer : set
        Set of all k-mers in the graph.

        
    Returns:

    tuple
        A tuple containing:
        - the constructed unitig (str),
        - the set of k-mers used to build it.
    """
    unitig = kmer
    used = {kmer}
    current = kmer

    while True:
        neighbors = left_neighbors(current, list_kmer)
        if len(neighbors) != 1:
            return unitig, used

        nxt = neighbors[0]
        unitig = nxt[0] + unitig
        used.add(nxt)

        # Stop in case of loop or circular genome
        if nxt == kmer or nxt == current:
            return unitig, used

        if (
            len(left_neighbors(nxt, list_kmer)) != 1
            or len(right_neighbors(nxt, list_kmer)) != 1
        ):
            return unitig, used

        current = nxt


def loop(file_list: str, k: int):
    """
    Build and compact a colored De Bruijn graph into unitigs.

    This function reads multiple FASTA files, builds a colored De Bruijn
    graph, and compacts it by merging linear paths into unitigs.

    
    Parameters:

    file_list : str
        Path to a text file listing FASTA file paths.
    k : int
        Length of the k-mers.

        
    Returns:

    tuple
        A tuple containing:
        - a dictionary mapping unitigs to their associated colors,
        - the set of original k-mers.
    """
    dbg = {}
    i = 0

    # Build the initial colored De Bruijn graph
    with open(file_list, "r") as fl:
        for file in fl:
            file = file.strip()
            dbg = dbg_builder(file, i, k, dbg)
            i += 1

    bag_of_kmer = set(dbg.keys())
    list_kmer = set(dbg.keys())
    final_dict = {}

    # Compact the graph into unitigs
    while list_kmer:
        current = next(iter(list_kmer))
        colors_unitig = dbg[current]

        left_uni, left_used = left_unitig(current, bag_of_kmer)
        right_uni, right_used = right_unitig(current, bag_of_kmer)

        unitig = left_uni[:-k] + right_uni
        used = left_used.union(right_used)

        final_dict[unitig] = sorted(colors_unitig)
        list_kmer.difference_update(used)

    return final_dict, bag_of_kmer
